version: '2'
services:
  django:
    build:
      context: ./src/django
      dockerfile: Dockerfile
    environment:
      - DJANGO_ENV=development
      - DJANGO_LOG_LEVEL=INFO
      - AWS_PROFILE=pfb
      - PFB_DB_HOST=database.service.pfb.internal
      - PFB_DB_DATABASE=pfb
      - PFB_DB_PASSWORD=pfb
      - PFB_DB_PORT=5432
      - PFB_DB_USER=pfb
      - PFB_SECRET_KEY=secret
      - PFB_AWS_BATCH_ANALYSIS_JOB_QUEUE_NAME
      - PFB_AWS_BATCH_ANALYSIS_JOB_DEFINITION_NAME_REVISION
      - PFB_AWS_BATCH_ANALYSIS_JOB_DEFINITION_NAME
      - PFB_AWS_BATCH_TILEMAKER_JOB_QUEUE_NAME
      - PFB_AWS_BATCH_TILEMAKER_JOB_DEFINITION_NAME_REVISION
      - PFB_AWS_BATCH_TILEMAKER_JOB_DEFINITION_NAME
    volumes:
      - $HOME/.aws:/root/.aws:ro
