#!/bin/bash

set -e

if [[ -n "${PFB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")

Publish container images to Elastic Container Registry (ECR) and
other artifacts to S3.
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

# If there's not already an AWS profile or key set, and a 'pfb' profile is defined, use that
if [[ -z "${AWS_PROFILE}" && -z "${AWS_ACCESS_KEY_ID}" && -n $(aws configure list-profiles | grep '^pfb$') ]]; then
    AWS_PROFILE=pfb
fi

DIR="$(dirname "$0")"

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        if [[ -n "${PFB_AWS_ECR_ENDPOINT}" ]]; then
            # Evaluate the return value of the get-login subcommand, which
            # is a docker login command with temporarily ECR credentials.
            aws ecr get-login-password | docker login --username AWS --password-stdin ${PFB_AWS_ECR_ENDPOINT}

            docker tag "pfb-nginx:${GIT_COMMIT}" \
                   "${PFB_AWS_ECR_ENDPOINT}/pfb-nginx:${GIT_COMMIT}"
            docker tag "pfb-app:${GIT_COMMIT}" \
                   "${PFB_AWS_ECR_ENDPOINT}/pfb-app:${GIT_COMMIT}"
            docker tag "pfb-analysis:${GIT_COMMIT}" \
                   "${PFB_AWS_ECR_ENDPOINT}/pfb-analysis:${GIT_COMMIT}"


            docker push "${PFB_AWS_ECR_ENDPOINT}/pfb-nginx:${GIT_COMMIT}"
            docker push "${PFB_AWS_ECR_ENDPOINT}/pfb-app:${GIT_COMMIT}"
            docker push "${PFB_AWS_ECR_ENDPOINT}/pfb-analysis:${GIT_COMMIT}"
        else
            echo "ERROR: No PFB_AWS_ECR_ENDPOINT variable defined."
            exit 1
        fi
    fi
fi
