#!/bin/bash

set -e

cd `dirname "${0}"`

if [[ -n "${PFD_DEBUG}" ]]; then
    set -x
fi

usage() {
    echo -n "$(basename "${0}") [OPTION]
Login to a running Docker container\'s shell.
Options:
    database   Database container
    django     Django container
    django-q   Django Q container
    angularjs  AngularJS container
    nginx      Nginx container
    tilegarden Tilegarden container
    help       Display this help text
"
}

case $1 in
    django|django-q|nginx|angularjs|tilegarden) NORMAL_CONTAINER=1 ;;
    database)         DATABASE_CONTAINER=1 ;;
    help|*)           usage; exit 1 ;;
esac

pushd ..

if [ -n "$NORMAL_CONTAINER" ]; then
    docker-compose exec "${1}" /bin/bash
fi

if [ -n "$DATABASE_CONTAINER" ]; then
    docker-compose exec database gosu postgres psql -d pfb
fi

popd
