#!/bin/bash

set -e

cd `dirname "${0}"`

if [[ -n "${PFB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Starts servers using docker-compose.

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        pushd ..

        docker-compose up nginx django django-q angularjs tilegarden

        popd
    fi
fi
