#!/bin/bash

set -e

if [[ -n "${PFB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Attempts to setup the project's development environment.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        git submodule sync && git submodule update
        vagrant up --provision
        vagrant ssh -c "cd /vagrant && ./scripts/update"
    fi
fi
