#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run application tests
"
}
DIR="$(dirname "$0")"

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
    	echo "running python tests..."
    	docker-compose -f "${DIR}/../docker-compose.yml" run \
			--rm --entrypoint "python3 manage.py test --noinput" django

        echo "running Tilegarden tests..."
        docker-compose run --rm --no-deps tilegarden yarn test

        echo "running angularjs linter..."
        docker-compose run --rm --no-deps angularjs gulp lint

        echo "running angularjs build..."
        docker-compose run --rm --no-deps angularjs gulp build

        echo "tests finished"
    fi
fi


