# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import pfb_analysis.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20170224_1639'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('IMPORTING', 'Importing Data'), ('BUILDING', 'Building Network Graph'), ('CONNECTIVITY', 'Calculating Connectivity'), ('METRICS', 'Calculating Graph Metrics'), ('EXPORTING', 'Exporting Results'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='CREATED', help_text='The current status of the AnalysisJob', max_length=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pfb_analysis_analysisjob_related+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pfb_analysis_analysisjob_related+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(help_text='Unique slug for neighborhood', max_length=256)),
                ('label', models.CharField(help_text='Human-readable label for neighborhood', max_length=256)),
                ('state_abbrev', localflavor.us.models.USStateField(help_text='The US state of the uploaded neighborhood', max_length=2)),
                ('boundary_file', models.FileField(help_text='A zipped shapefile boundary to run the bike network analysis on', upload_to=pfb_analysis.models.get_neighborhood_file_upload_path)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='users.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='pfb_analysis.Neighborhood'),
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together=set([('name', 'organization')]),
        ),
    ]
