# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pfb_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='created_by',
            field=models.ForeignKey(default='bba2038e-863e-4c1e-a64c-c06b6000a61f', on_delete=django.db.models.deletion.PROTECT, related_name='pfb_analysis_neighborhood_related+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='modified_by',
            field=models.ForeignKey(default='bba2038e-863e-4c1e-a64c-c06b6000a61f', on_delete=django.db.models.deletion.PROTECT, related_name='pfb_analysis_neighborhood_related+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
