# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0002_auto_20170307_1640'),
        ('pfb_analysis', '0002_analysisjob_batch_job_id'),
    ]

    operations = [
    ]
