# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0003_merge_20170307_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='osm_extract_url',
            field=models.URLField(blank=True, help_text='Load OSM data for this neighborhood from a URL rather than pulling from Overpass API. The url must have a .osm file extension and may optionally be compressed via zip/bzip/gz, e.g. http://a.com/foo.osm or http://a.com/foo.osm.bz2', max_length=2048, null=True),
        ),
    ]
