# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0003_merge_20170307_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJobStatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('IMPORTING', 'Importing Data'), ('BUILDING', 'Building Network Graph'), ('CONNECTIVITY', 'Calculating Connectivity'), ('METRICS', 'Calculating Graph Metrics'), ('EXPORTING', 'Exporting Results'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], max_length=12)),
                ('step', models.CharField(max_length=50)),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='pfb_analysis.AnalysisJob')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
