# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0004_analysisjobstatusupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisjob',
            name='status',
        ),
    ]
