# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0004_auto_20170317_2018'),
        ('pfb_analysis', '0005_remove_analysisjob_status'),
    ]

    operations = [
    ]
