# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0004_analysisjob_osm_extract_url'),
        ('pfb_analysis', '0005_remove_analysisjob_status'),
    ]

    operations = [
    ]
