# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0007_auto_20170322_1309'),
        ('pfb_analysis', '0006_merge_20170322_1647'),
    ]

    operations = [
    ]
