# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 13:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0009_auto_20170323_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='overall_scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default=dict),
        ),
    ]
