# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0010_analysisjob_overall_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='census_block_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
