# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0011_analysisjob_census_block_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisScoreMetadata',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text='Short descriptive name', max_length=256, null=True)),
                ('category', models.CharField(blank=True, help_text='Used to group scores with the same category together', max_length=128, null=True)),
                ('description', models.CharField(blank=True, help_text='Long description of the metric', max_length=1024, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
