# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0012_analysisscoremetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjobstatusupdate',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('IMPORTING', 'Importing Data'), ('BUILDING', 'Building Network Graph'), ('CONNECTIVITY', 'Calculating Connectivity'), ('METRICS', 'Calculating Graph Metrics'), ('EXPORTING', 'Exporting Results'), ('EXPORTED', 'Analysis Finished'), ('TILING', 'Generating Map Tiles'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], max_length=12),
        ),
    ]
