# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 15:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0013_auto_20170407_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
