# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import pfb_analysis.models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0013_auto_20170407_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='_analysis_job_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='_tilemaker_job_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='analysis_job_definition',
            field=models.CharField(default=pfb_analysis.models.generate_analysis_job_def, max_length=50),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='tilemaker_job_definition',
            # Formerly had 'default=pfb_analysis.models.generate_tilemaker_job_def', but that crashes
            field=models.CharField(default='', max_length=50),
        ),
    ]
