# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0014_auto_20170412_1611'),
        ('pfb_analysis', '0015_add_neighborhood_geoms'),
    ]

    operations = [
    ]
