# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 14:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0016_merge_20170412_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='geom_pt',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
