# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 14:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


def set_neighborhood_geom_pt(apps, schema_editor):
    Neighborhood = apps.get_model("pfb_analysis", "Neighborhood")
    for n in Neighborhood.objects.all():
        n.geom_pt = n.geom.centroid
        n.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0017_neighborhood_geom_pt'),
    ]

    operations = [
        migrations.RunPython(set_neighborhood_geom_pt)
    ]
