# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_last_job(apps, schema_editor):
    Neighborhood = apps.get_model('pfb_analysis', 'Neighborhood')
    AnalysisJob = apps.get_model('pfb_analysis', 'AnalysisJob')
    for neighborhood in Neighborhood.objects.all():
        jobs = AnalysisJob.objects.filter(neighborhood=neighborhood).order_by('-modified_at')
        for job in jobs:
            last_update = job.status_updates.last()
            if last_update and last_update.status == 'COMPLETE':
                neighborhood.last_job = job
                neighborhood.save()
                break

        # if have no completed job, go with the last modified job
        if not neighborhood.last_job and jobs.count():
            neighborhood.last_job = jobs[0]
            neighborhood.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0021_neighborhood_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='last_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_job_neighborhood', to='pfb_analysis.AnalysisJob'),
        ),
        migrations.RunPython(set_last_job, reverse_code=migrations.RunPython.noop),
    ]
