# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 21:10
from __future__ import unicode_literals

from django.db import migrations, models


def set_last_status(apps, schema_editor):
    AnalysisJob = apps.get_model('pfb_analysis', 'AnalysisJob')
    for job in AnalysisJob.objects.all():
        latest_update = job.status_updates.last()
        job.last_status = latest_update.status if latest_update else 'CREATED'
        first_update = job.status_updates.filter(status='IMPORTING').first()
        if first_update:
            job.start_time = first_update.timestamp
            if job.last_status in ('COMPLETE', 'CANCELLED', 'ERROR',):
                diff = latest_update.timestamp - job.start_time
                job.final_runtime = int(diff.total_seconds())
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0022_neighborhood_last_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='final_runtime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='last_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('IMPORTING', 'Importing Data'), ('BUILDING', 'Building Network Graph'), ('CONNECTIVITY', 'Calculating Connectivity'), ('METRICS', 'Calculating Graph Metrics'), ('EXPORTING', 'Exporting Results'), ('EXPORTED', 'Analysis Finished'), ('TILING', 'Generating Map Tiles'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], default='CREATED', max_length=12),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_last_status, reverse_code=migrations.RunPython.noop),
    ]
