# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0023_auto_20170509_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisjob',
            old_name='last_status',
            new_name='status',
        ),
    ]
