# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170509_1559'),
        ('pfb_analysis', '0025_auto_20170511_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='label',
            field=models.CharField(help_text='Human-readable label for neighborhood, should not include State', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together=set([('name', 'state_abbrev', 'organization')]),
        ),
    ]
