# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 13:19
from __future__ import unicode_literals
import re
from django.utils.text import slugify

from django.db import migrations


def remove_states_from_labels(apps, schema_editor):
    Neighborhood = apps.get_model("pfb_analysis", "Neighborhood")
    for n in Neighborhood.objects.all():
        # Remove state abbreviation from label
        n.label = re.sub(r', *[A-Z]{2} *$', '', n.label)
        # Set name to new slugified label
        n.name = slugify(n.label)
        n.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0026_auto_20170517_1531'),
    ]

    operations = [
        migrations.RunPython(remove_states_from_labels, reverse_code=migrations.RunPython.noop),
    ]
