# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0027_remove_states_from_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisscoremetadata',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Determines sort order in response, lower numbers sort first', null=True),
        ),
    ]
