# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0028_analysisscoremetadata_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], default='public', max_length=10),
        ),
    ]
