# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0029_auto_20170802_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='osm_extract_url',
            field=models.URLField(blank=True, help_text='Load OSM data for this neighborhood from a URL rather than pulling from Goefabrik extracts. The url must be to an uncompressed OSM file (with .osm extension) or a compressed OSM file (with .osm.zip, .osm.gzip, .osm.bz2, or .osm.pbf extension). e.g. http://a.com/foo.osm or http://a.com/foo.osm.bz2', max_length=2048, null=True),
        ),
    ]
