# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 21:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0030_auto_20180419_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusBlocksResults',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='census_block_results', to='pfb_analysis.AnalysisJob')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodWaysResults',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('tf_seg_str', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ft_seg_str', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('xwalk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ft_bike_in', models.CharField(blank=True, max_length=20, null=True)),
                ('tf_bike_in', models.CharField(blank=True, max_length=20, null=True)),
                ('functional', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_way_results', to='pfb_analysis.AnalysisJob')),
            ],
        ),
    ]
