# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 15:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0030_auto_20180419_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='census_blocks_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='neighborhood_ways_geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
    ]
