# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-12 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pfb_analysis', '0033_auto_20181205_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLocalUploadTask',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('importing', 'Importing'), ('complete', 'Complete'), ('error', 'Error')], default='created', max_length=16)),
                ('error', models.CharField(blank=True, max_length=8192, null=True)),
                ('upload_results_url', models.URLField(max_length=8192)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pfb_analysis_analysislocaluploadtask_related+', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_upload_task', to='pfb_analysis.AnalysisJob')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pfb_analysis_analysislocaluploadtask_related+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
