# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-24 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0034_add_analysislocaluploadtask_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysislocaluploadtask',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('IMPORTING', 'Importing'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='CREATED', max_length=16),
        ),
    ]
