# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-31 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0035_auto_20190124_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='city_fips',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
