# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-14 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0036_neighborhood_city_fips'),
    ]

    operations = [
        migrations.CreateModel(
            name='TilegardenWarmingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
