# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-27 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0036_neighborhood_city_fips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisjob',
            name='_tilemaker_job_name',
        ),
        migrations.RemoveField(
            model_name='analysisjob',
            name='tilemaker_job_definition',
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('IMPORTING', 'Importing Data'), ('BUILDING', 'Building Network Graph'), ('CONNECTIVITY', 'Calculating Connectivity'), ('METRICS', 'Calculating Graph Metrics'), ('EXPORTING', 'Exporting Results'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], default='CREATED', max_length=12),
        ),
        migrations.AlterField(
            model_name='analysisjobstatusupdate',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('IMPORTING', 'Importing Data'), ('BUILDING', 'Building Network Graph'), ('CONNECTIVITY', 'Calculating Connectivity'), ('METRICS', 'Calculating Graph Metrics'), ('EXPORTING', 'Exporting Results'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('ERROR', 'Error')], max_length=12),
        ),
    ]
