# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-01 19:00
from __future__ import unicode_literals

import logging
import us
from django.db import migrations

logger = logging.getLogger(__name__)


def move_territories_to_us(apps, schema_editor):
    """ Move neighborhoods with a US territory as 'country' into the US """
    Neighborhood = apps.get_model("pfb_analysis", "Neighborhood")
    for n in Neighborhood.objects.filter(country__in=[t.abbr for t in us.TERRITORIES]):
        n.state_abbrev = n.country
        n.country = 'US'
        n.save()
        logger.info('Moved {}, {}, into the US.'.format(n.label, n.state_abbrev))



def move_territories_out_of_us(apps, schema_editor):
    """ Move neighborhoods with a US territory as 'state_abbrev' into their own countries """
    Neighborhood = apps.get_model("pfb_analysis", "Neighborhood")
    for n in Neighborhood.objects.filter(state_abbrev__in=[t.abbr for t in us.TERRITORIES]):
        n.country = n.state_abbrev
        n.state_abbrev = ''
        n.save()
        logger.info('Moved {}, {}, out of the US.'.format(n.label, n.country))


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0037_auto_20190227_2110'),
    ]

    operations = [
        migrations.RunPython(move_territories_to_us, reverse_code=move_territories_out_of_us)
    ]
