# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-06 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0038_move_territories_to_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='state_abbrev',
            field=models.CharField(blank=True, help_text='The state/province of the uploaded neighborhood', max_length=10, null=True),
        ),
    ]
