# Generated by Django 2.2.5 on 2019-11-11 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0039_alter_neighborhood_state_abbrev_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='last_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_job_neighborhood', to='pfb_analysis.AnalysisJob'),
        ),
    ]
