# Generated by Django 2.2.10 on 2020-10-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0040_neighborhood_analysis_job_ondelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='default_speed_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='speed_limit_src',
            field=models.CharField(blank=True, choices=[('State', 'State'), ('City', 'City')], max_length=20, null=True),
        ),
    ]
