# Generated by Django 2.2.16 on 2022-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0041_auto_20201006_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='max_trip_distance',
            field=models.PositiveIntegerField(blank=True, default=2680, null=True),
        ),
    ]
