# Generated by Django 3.2.13 on 2022-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0042_analysisjob_max_trip_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='overall_scores',
            field=models.JSONField(db_index=True, default=dict),
        ),
    ]
