# Generated by Django 3.2.13 on 2022-06-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0043_update_jsonfield_django_32'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='population_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
