# Generated by Django 3.2.13 on 2022-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0045_analysisjob_skip_import_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='jobs_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
