# Generated by Django 3.2.13 on 2022-08-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0046_analysisjob_jobs_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='speed_limit',
            field=models.IntegerField(blank=True, help_text='The default residential speed limit, in MPH', null=True),
        ),
    ]
