# Generated by Django 3.2.13 on 2022-12-05 20:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfb_analysis', '0048_crash'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='geog',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.RunSQL(
            "UPDATE pfb_analysis_neighborhood SET geog = geom;",
            migrations.RunSQL.noop
        )
    ]
