# Generated by Django 4.2.17 on 2024-12-19 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pfb_analysis', '0049_neighborhood_geog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisbatch',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysislocaluploadtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysislocaluploadtask',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related+', to=settings.AUTH_USER_MODEL),
        ),
    ]
