# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfbuser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Organization'),
        ),
    ]
