---

- name: Install shp2pgsql (requires postgis package)
  apt: name=postgis

- name: Install unzip package (used by analysis importers)
  apt: name=unzip

- name: Install parallel package (used by analysis)
  apt: name=parallel

- name: Install python-gdal (used to autodetect SRID for import)
  apt: name=python-gdal

- name: Create PostgreSQL super user
  become_user: postgres
  postgresql_user: name="{{ postgresql_database_user }}"
                   password="{{ postgresql_database_password }}"
                   role_attr_flags=SUPERUSER
                   state=present

- name: Create PFB database
  become_user: postgres
  postgresql_db: name="{{ postgresql_database_name }}"
                  owner="{{ postgresql_database_user }}"
                  encoding=UTF-8

- name: Add postgis extension to PFB database
  become_user: postgres
  postgresql_ext: name=postgis db="{{ postgresql_database_name }}"

- name: Add uuid-ossp extension to PFB database
  become_user: postgres
  postgresql_ext: name=uuid-ossp db="{{ postgresql_database_name }}"

- name: Add hstore extension to PFB database
  become_user: postgres
  postgresql_ext: name=hstore db="{{ postgresql_database_name }}"

- name: Install plpythonu package
  apt: name="postgresql-plpython-{{ postgresql_version }}"

- name: Add plpythonu language to PFB database
  become_user: postgres
  postgresql_lang: lang=plpythonu db="{{ postgresql_database_name }}"

- name: Install pgrouting
  apt: name="postgresql-{{ postgresql_version }}-pgrouting"

- name: Add pgrouting extension to PFB database
  become_user: postgres
  postgresql_ext: name=pgrouting db="{{ postgresql_database_name }}"

- include: "install_osm2pgsql.yml"

- include: "install_osm2pgrouting.yml"

- include: "install_quantile_extension.yml"

- include: "install_tdg_extension.yml"

- meta: flush_handlers

- name: Update postgresql search path in user db
  command: psql -U "{{ postgresql_database_user }}" -d "{{ postgresql_database_name }}" -h "{{ postgresql_database_host }}" -c 'ALTER USER {{ postgresql_database_user }} SET search_path TO generated,received,scratch,"$user",tdg,public;'
