#!/bin/bash

yarn claudia create --config claudia/claudia.json --no-optional-dependencies \
    --api-module dist/api \
    --name ${LAMBDA_FUNCTION_NAME} \
    --region ${LAMBDA_REGION} \
    --role "${LAMBDA_FUNCTION_NAME}Executor" \
    ${LAMBDA_TIMEOUT:+--timeout ${LAMBDA_TIMEOUT}} \
    ${LAMBDA_MEMORY:+--memory ${LAMBDA_MEMORY}} \
    ${LAMBDA_SECURITY_GROUPS:+--security-group-ids ${LAMBDA_SECURITY_GROUPS}} \
    ${LAMBDA_SUBNETS:+--subnet-ids ${LAMBDA_SUBNETS}} \
    --set-env PFB_DB_HOST=${PFB_DB_HOST},PFB_DB_DATABASE=${PFB_DB_DATABASE},PFB_DB_PASSWORD=${PFB_DB_PASSWORD},PFB_DB_PORT=${PFB_DB_PORT},PFB_DB_USER=${PFB_DB_USER},${PFB_TILEGARDEN_CACHE_BUCKET:+PFB_TILEGARDEN_CACHE_BUCKET=${PFB_TILEGARDEN_CACHE_BUCKET}}
