name: CI

on:
  push:
    branches:
      - develop
      - release/**
      - test/**
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      PFB_AWS_BATCH_ANALYSIS_JOB_QUEUE_NAME: "dummy-test-pfb-analysis-job-queue"
      PFB_AWS_BATCH_ANALYSIS_JOB_DEFINITION_NAME_REVISION: "dummy-test-pfb-analysis-run-job:1"
      PFB_AWS_ECR_ENDPOINT: ${{ secrets.PFB_AWS_ECR_ENDPOINT }}
      AWS_DEFAULT_REGION: "us-east-1"
      PFB_SETTINGS_BUCKET: "staging-pfb-config-us-east-1"
      PFB_S3STORAGE_BUCKET: "staging-pfb-static-us-east-1"
      BATCH_ANALYSIS_JOB_NAME_REVISION: "dummy-test-pfb-analysis-run-job:1"
      GIT_COMMIT: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - run: ./scripts/update

      - name: CI Build
        run: ./scripts/cibuild

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: CI Publish
        run: ./scripts/cipublish
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/test/')

      - name: Infra Plan and Apply
        run: |
          unset AWS_PROFILE
          ./scripts/infra plan
          ./scripts/infra apply
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/test/')
